# Generated by Django 3.1.1 on 2023-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20231026_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='year_of_study',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voter',
            name='year_of_study',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
