# Generated by Django 3.1.1 on 2023-10-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20231027_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionMilbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.TextField(max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('plaintif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_complaint', to='voting.voter')),
            ],
        ),
    ]
