# Generated by Django 3.1.1 on 2023-10-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_electionmilbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionMilboxReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionmailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_complaint', to='voting.electionmilbox')),
            ],
        ),
    ]
