# Generated by Django 3.1.1 on 2023-10-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_electionmilboxreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionmilboxreply',
            name='electionmailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_complaint_reply', to='voting.electionmilbox'),
        ),
    ]
