# Generated by Django 3.1.1 on 2023-10-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20231028_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionmilboxreply',
            name='reply',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
