# Generated by Django 4.2 on 2023-11-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0011_alter_candidate_id_alter_electionmilbox_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electionresultpdf",
            name="report",
            field=models.FileField(upload_to="results/"),
        ),
    ]
