# Generated by Django 4.2 on 2023-11-18 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0012_alter_electionresultpdf_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="photo",
        ),
    ]
