# Generated by Django 4.2.7 on 2023-11-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0013_remove_candidate_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="year_of_study",
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="voter",
            name="year_of_study",
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=2),
        ),
    ]
